version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      # using host port as 3307 inorder to avoid conflict with local machine's mysql
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  service-registry:
    build: ./service_registry
    container_name: service-registry
    ports:
      - "8761:8761"  # Map internal port to host port

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - service-registry
    environment:
      SPRING_DATASOURCE_URL:    jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  habit-service:
    build: ./habit-service
    container_name: habit-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - service-registry
    environment:
      SPRING_DATASOURCE_URL:    jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  habit-status-service:
    build: ./habit-status-service
    container_name: habit-status-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - service-registry
    environment:
      SPRING_DATASOURCE_URL:    jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - user-service

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8090:8090"
    depends_on:
      - service-registry
      - user-service
      - habit-service
      - habit-status-service
      - auth-service

volumes:
  mysql_data:
